### ISSUE TITLE
example for collection

### ISSUE THREAD

**Issue by mmintel** [coniel/meteor-react-form-handler#10]
hi there,

I am really new to using react with meteor. your package seems really nice, but could you give an example on how to deal with collection using your package? e.g. inserting and updating a document.

cheers
Marc

**Comment by coniel** [comment]
The package doesn't do this automatically like autoform (I assume you're coming from that). Basically you need to do the database part yourself in the onSubmit callback. Say you have a `Books` collection and you want a form to create a new book:

```
NewBookForm = React.createClass({
    _onSubmit(doc) {
        Books.insert(doc);
    },
    render() {
        return (
            <Form schema={BookSchema} id="new-book-form" onSubmit={this._onSubmit}>
                <TextInput name="title" />
                <TextInput name="author" />
                <TextArea name="summary" />
                <SubmitButton label="Save" />
            </Form>
        )
    }
});
```

You can even use the same form for updating with a few modifications:

```
NewBookForm = React.createClass({
    _onSubmit(doc) {
        if (doc._id) {
            Books.update({_id: doc._id}, {$set: doc});
        } else {
            Books.insert(doc);
        }
    },
    render() {
        return (
            <Form schema={BookSchema} id="new-book-form" onSubmit={this._onSubmit} doc={someExistingBook}>
                <TextInput name="title" />
                <TextInput name="author" />
                <TextArea name="summary" />
                <SubmitButton label="Save" />
            </Form>
        )
    }
});
```

If you are making an update form, make sure you've added `_id` to the list of ignored fields or else you will get an error when submitting the form (I should probably make it ignored by default actually):

```
Meteor.startup(function() {
    FormHandler.ignoreFields = ["_id"]
});
```

**Comment by mmintel** [comment]
thanks for your reply!

given the following schema:
```js
FoodSchema = new SimpleSchema({
    name: {
        type: String,
        label: "Name",
        max: 200
    },
    createdAt: {
      type: Date,
      autoValue: function() {
        if (this.isInsert) {
          return new Date();
        } else if (this.isUpsert) {
          return {$setOnInsert: new Date()};
        } else {
          this.unset();  // Prevent user from supplying their own value
        }
      }
    },
    updatedAt: {
      type: Date,
      autoValue: function() {
        if (this.isUpdate) {
          return new Date();
        }
      },
      denyInsert: true,
      optional: true
    }
});
```

and this component

```jsx
FoodsCreate = React.createClass({
    // This mixin makes the getMeteorData method work
    mixins: [ReactMeteorData],

    // Loads items from the Tasks collection and puts them on this.data.tasks
    getMeteorData() {
        return {tasks: Foods.find({}).fetch()}
    },

    _onSubmit(doc) {
        Foods.insert(doc);
    },

    render() {
        return (
            <div className="container">
                <h1>Create new Food</h1>
                <Form schema={FoodSchema} id="food-create-form" onSubmit={this._onSubmit} resetOnSubmit>
                    <TextInput name="name" />
                    <SubmitButton label="Register" onClick={this._onSubmit} />
                </Form>
            </div>
        )
    }
});
```

throws this error on submit
```
insert failed: Error: Name is required
```

but I cannot find the bug.. it looks like your example. do you have an idea? something wrong with TextInput?

**Comment by coniel** [comment]
There's a couple of things going on. First of all the form submission is failing because `createdAt` is required by the schema and you don't have an input for it in your form. I should have been clearer before: the schema passed to the form should only contain values for which you will have an input (so in the case the schema should only contain `name`). In my own apps I have a helper method to retrieve part of a schema (so for your form I would do `schema={getSubSchema(FoodSchema, ["name"])}`.

I'm still thinking of the best approach to that particular issue. I was going to include a getSubSchema helper method, but now I'm thinking of perhaps making it so that the form only validates the inputs and ignores the rest of the schema (I think that's how autoform does it). In the mean time, you can use my helper method if you want: https://gist.github.com/coniel/4b4470bc68d4fcb89d3c

The second problem is that you've added `onClick={this._onSubmit}` to the SubmitButton. It shouldn't have any `onClick` action at all (it's just a regular HTML submit button and the form has it's own `onSubmit` callback). So in your case the form submission itself is failing because of the createdAt thing, but the _onSubmit method is being called anyway because of the onClick handler. Since it's being called by the button click there is no `doc` passed to it so the insert fails.

So to fix it:
- Pass in a schema containing only `name`
- Remove onClick from the SubmitButton

Also, in future, if you want to manually submit the form (e.g. from a button outside of the form) use `this.refs.myForm.submit()` (and set `ref="myForm"` on the Form component). And another thing, you don't need to add `resetOnSubmit` to the Form. Forms are reset on submit by default (to disable it add `resetOnSubmit={false}`).

**Comment by mmintel** [comment]
thanks again! Now its working just fine if I remove everything except "name" from the schema. Adding it back again and using your helper method throws `Uncaught TypeError: Cannot read property 'type' of undefined`.

**Comment by coniel** [comment]
Ah, there was a bug in it. Try it now.

**Comment by mmintel** [comment]
yeaah thats working, thanks for the nice help!

**Comment by coniel** [comment]
No problem, let me know if you need any more help.

**Comment by mmintel** [comment]
Sorry to disturb you again, but I think I have "the same problem" with updating documents. Now I have a code that looks like this

```JSX
    mixins: [ReactMeteorData],
    propTypes: {
      _id: React.PropTypes.string.isRequired
    },
    getMeteorData() {
        return {
            food: Foods.findOne({_id:this.props._id})
        }
    },

    _onSubmit(doc) {
        Foods.update({_id:this.props._id}, {$set: doc});
        console.log(doc);
    },

    render() {
        return (
            <div className="container">
                <h1>Edit "{this.data.food.name}"</h1>
                <Form schema={getSubSchema(FoodSchema, ["name", "description", "price"])} id="food-edit-form" onSubmit={this._onSubmit} doc={this.data.food}>
                    <TextInput name="name" />
                    <TextArea name="description" />
                    <TextInput type="number" name="price" />
                    <SubmitButton label="Save" />
                </Form>
            </div>
        )
    }
});
```

All data of the doc is displayed in the form, so that works just fine. However when trying to edit that field I am getting this here:

```
React form handler validation errors Object {_id: "keyNotInSchema", createdAt: "keyNotInSchema"}
```

How can I deal with this?
Thanks!

**Comment by coniel** [comment]
Hey, no worries. Have you set the ignored fields? I need to update the package so that this isn't necessary, but for now add this somewhere with the rest of your startup configurations:

```
Meteor.startup(function() {
    FormHandler.ignoreFields = ["_id", "createdAt"]
});
```

Keep in mind that this means these fields are always ignored when validating any form (so if you have a form with a createdAt input, it will not be validated). I'll try get an update out today that makes all of this unnecessary, so it just works.

**Comment by mmintel** [comment]
Thanks! That's great news :)) It works so far, just the reactivity is not working. E.g. I change the "name" field and update the document the name in the heading is not being updated until refresh.

**Comment by coniel** [comment]
Could you post an example? I don't think that is an issue with the form handler. Sounds more like you are fetching your heading from a non-reactive source.

**Comment by mmintel** [comment]
is the same example like above there is the line
```
                <h1>Edit "{this.data.food.name}"</h1>

**Comment by coniel** [comment]
Oh right, didn't see the header. That is weird indeed, the code looks fine. If the update form is actually updating the document (which it appears to be since you say it changes when refreshing) then the problem is something else. Can you do a quick check to see if minimongo is being updated correctly by editing you onSubmit method:

```
_onSubmit(doc) {
    Foods.update({_id:this.props._id}, {$set: doc});
    console.log(Foods.findOne({_id:this.props._id}));
    console.log(doc);
}
```
If the document returned by that query matches the updates from the form then the problem is simply that the component is not re-rendering, otherwise it's something else.

**Comment by mmintel** [comment]
ah the problem was that I also had to add "updatedAt" to ignored fields. so this works now but after saving the form the input field jumps back to the old value. this also just updates after refreshing the whole page.

thats the console log output
```
Object {_id: "MSeZhWMAmwa3D3qSv", name: "asdtesto", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:17 Object {name: "asdtesto", description: "adsad", price: 123, updatedAt: Sun Feb 21 2016 13:36:12 GMT+0100 (CET)}
```

**Comment by coniel** [comment]
Could you add the same console.log to getMeteorData (make sure it's before the return). Does it get called when you submit, and if so how does it compare to the one returned from onSubmit?

**Comment by mmintel** [comment]
this is the log when I just refreshed the page

```
edit.jsx:9 INSIDE getMeteorData:
edit.jsx:10 Foods.findOne: 
edit.jsx:11 Object {_id: "MSeZhWMAmwa3D3qSv", name: "oldtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:12 doc: 
edit.jsx:13 undefined
```

and this appears after adding changing the name to "newtest" and saving it.

```
INSIDE _onSubmit:
edit.jsx:22 Foods.findOne: 
edit.jsx:23 Object {_id: "MSeZhWMAmwa3D3qSv", name: "newtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:24 doc: 
edit.jsx:25 Object {name: "newtest", description: "adsad", price: 123, updatedAt: Sun Feb 21 2016 16:08:05 GMT+0100 (CET)}
edit.jsx:9 INSIDE getMeteorData:
edit.jsx:10 Foods.findOne: 
edit.jsx:11 Object {_id: "MSeZhWMAmwa3D3qSv", name: "newtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:12 doc: 
edit.jsx:13 undefined
edit.jsx:9 INSIDE getMeteorData:
edit.jsx:10 Foods.findOne: 
edit.jsx:11 Object {_id: "MSeZhWMAmwa3D3qSv", name: "newtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:12 doc: 
edit.jsx:13 undefined
```

**Comment by coniel** [comment]
That's odd, the header should be updating since the data returned by getMeteorData has clearly changed. Can you try adding the same console.log to the render method to see what that gives. Also, remove the console.log(doc) from getMeteorData since it's undefined it could be causing problems.

**Comment by mmintel** [comment]
this is here is before changing the form:

```
INSIDE getMeteorData:
edit.jsx:10 Foods.findOne: 
edit.jsx:11 Object {_id: "MSeZhWMAmwa3D3qSv", name: "oldtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:29 INSIDE render():
edit.jsx:30 Foods.findOne: 
edit.jsx:31 Object {_id: "MSeZhWMAmwa3D3qSv", name: "oldtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:32 doc: 
edit.jsx:33 undefined
```

and this is after saving the form:

```
INSIDE _onSubmit:
edit.jsx:22 Foods.findOne: 
edit.jsx:23 Object {_id: "MSeZhWMAmwa3D3qSv", name: "newtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:24 doc: 
edit.jsx:25 Object {name: "newtest", description: "adsad", price: 123, updatedAt: Sun Feb 21 2016 20:52:46 GMT+0100 (CET)}
edit.jsx:9 INSIDE getMeteorData:
edit.jsx:10 Foods.findOne: 
edit.jsx:11 Object {_id: "MSeZhWMAmwa3D3qSv", name: "newtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:29 INSIDE render():
edit.jsx:30 Foods.findOne: 
edit.jsx:31 Object {_id: "MSeZhWMAmwa3D3qSv", name: "newtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:32 doc: 
edit.jsx:33 undefined
edit.jsx:9 INSIDE getMeteorData:
edit.jsx:10 Foods.findOne: 
edit.jsx:11 Object {_id: "MSeZhWMAmwa3D3qSv", name: "newtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:29 INSIDE render():
edit.jsx:30 Foods.findOne: 
edit.jsx:31 Object {_id: "MSeZhWMAmwa3D3qSv", name: "newtest", description: "adsad", price: 123, createdAt: Sat Feb 20 2016 18:30:18 GMT+0100 (CET)…}
edit.jsx:32 doc: 
edit.jsx:33 undefined
```
