### ISSUE TITLE
Default value for semantic-ui dropdown

### ISSUE THREAD

**Issue by davidschenz** [coniel/meteor-react-form-handler#4]
Hi again - I'm struggling a bit with specifying default value for a drop down with semantic-ui. For a text value, I'm merely doing:

`<TextInput name="name" layoutStyle="first-half" defaultValue={this.data.attribute.name}/>`

but on a select, if I do the same: 

`<Select name="type" useAllowedValues layoutStyle="second-half" defaultText={this.data.attribute.type} />`

it doesn't populate the value. 

![image](https://cloud.githubusercontent.com/assets/7108554/11459946/6bc12502-96b0-11e5-93f9-61371a23e444.png)

Some of the information on the dropdown is here:

http://semantic-ui.com/modules/dropdown.html#/usage

Thanks again

David

**Comment by coniel** [comment]
Hey, sorry for the delay in replying. Turns out I forgot to implement default value for the Select component. It's now been added, as well as the ability to add a placeholder.

So you can either do: 

`<Select  name="type" useAllowedValues layoutStyle="second-half" defaultValue="someValue" />`

or 

`<Select  name="type" useAllowedValues layoutStyle="second-half" placeholder="Please select..." />`

Placeholder can also be set from the schema (will add schema support for default value soon as well).
