### ISSUE TITLE
get rid of ids

### ISSUE THREAD

**Issue by macrozone** [coniel/meteor-react-form-handler#5]
Hi, thank you for your effort!

One major issue with autoform is, that it requires htm-ids on the forms.

This will cause a lot of problems, because you can no longer re-use the same component, if they occure multiple times on the same page.

Generating and using unique-ids (with Random.id()) may be a solution, but looks like a hack. I would try to avoid them completely.

**Comment by coniel** [comment]
I don't know if it would be possible to get rid of ids, since the form definitively needs some sort of unique identifier in order to store and retrieve the data. If you create a component with a form inside and want to use it multiple times, you could pass the form id in as a prop, or create a unique one inside the component based on another prop (e.g. the parent's _id).

For example, let's say you have a list of posts and you want each one to have a comment form, you could do something like:

```
// To render the post list:
{this.data.posts.map(function(post) {
    return (
        // Post content //
        <PostCommentForm postId={post._id} />
    )
})}

// The render method of PostCommentForm:
render() {
    return (
        <Form id={"post-comment-form-" + this.props.postId} ...>
            // form inputs...
        </Form>
    )
}
```

If your use case doesn't have any sort of parent id available to generate a unique id, you could always use Random.id() yourself:

```
// In the component containing the form:
getInitialState() {
    return {
        formId: Random.id()
    }
},
render() {
    return (
        <Form id={this.state.formId} ...>
            // form inputs...
        </Form>
    )
}
```

**Comment by macrozone** [comment]
You can store all the data in the state of the <Form>-component, so why you would need an id? 

If you iterate in react, you need to pass a unique-key-property anyway. I would not introduce a new id that you have to manage.

**Comment by coniel** [comment]
The problem with storing the data inside the React components state is that it will be lost on a hot-code-push reload (currently it's stored in a ReactiveDict, which will soon be setup to handle hot-code-push reloads and restore the form state as it was). Plus in this way, the form values can easily be accessed from outside, even when you don't have access to the form component itself (using `FormHandler.getFormDoc(formId);`).

Also, as you said, when you iterate in React you need a unique key prop. You could just use that as the form id as well.

One option to make things easier would be to make the id prop optional. So you can still set a specific form id if you need it, otherwise it is automatically generated using something like Random.id().

**Comment by macrozone** [comment]
Hi Coniel, thank you for your answer.

I understand your point. Maybe the easiest way is indeed to create it randomly, if not present.

**Comment by coniel** [comment]
There might actually be a solution to this based on #8 (will merge soon) which fetches the input values directly. The only remaining issue is surviving hot code pushes.
